# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 808c39ae2a75faed7794af3d6e961033076724a87c2f4355c6b742436f4337f4e3cfe55b1ec5206645620a6d2ec772693f1b6c40e74144dc95708c86136bb3fb

test:
  secret_key_base: 107bd57073374ac17935338243e63f0e9ea2ebf1adb2667262d69002b062963faab76b99a6012f1ce9c1a3df07c67f58e60365642e2d420c277065058a306b30

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
